[[rocm_smi_lib]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a890e7b69510b345be328713ad7a018362714c20"
libc = "glibc"
os = "linux"

    [[rocm_smi_lib.download]]
    sha256 = "9150b4a567462e8a43d516f37f6d4db6cb2573544f8122bb6a43d49a451ac33c"
    url = "https://github.com/JuliaBinaryWrappers/rocm_smi_lib_jll.jl/releases/download/rocm_smi_lib-v4.2.0+0/rocm_smi_lib.v4.2.0.x86_64-linux-gnu-cxx03.tar.gz"
[[rocm_smi_lib]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "df5a32fd83d591401422b3093c55b6d25d6515e7"
libc = "glibc"
os = "linux"

    [[rocm_smi_lib.download]]
    sha256 = "b62173773d10b5e800701471f62fa22daaf65e6980ee0aa26c2a5b3de3d94d2c"
    url = "https://github.com/JuliaBinaryWrappers/rocm_smi_lib_jll.jl/releases/download/rocm_smi_lib-v4.2.0+0/rocm_smi_lib.v4.2.0.x86_64-linux-gnu-cxx11.tar.gz"
[[rocm_smi_lib]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8da65175e255caaa79dcdd256bfed0ac0378684d"
libc = "musl"
os = "linux"

    [[rocm_smi_lib.download]]
    sha256 = "eae92366beedf1181cd95a78136ea573f6dad8f1ed02a3424428a1a9d75e5ef6"
    url = "https://github.com/JuliaBinaryWrappers/rocm_smi_lib_jll.jl/releases/download/rocm_smi_lib-v4.2.0+0/rocm_smi_lib.v4.2.0.x86_64-linux-musl-cxx03.tar.gz"
[[rocm_smi_lib]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b358c11e09fc4e7f4cd969f1182a5b9253a62a01"
libc = "musl"
os = "linux"

    [[rocm_smi_lib.download]]
    sha256 = "8e4352646314674c4c58826a6605b17cdbd501011b0ff7fa8ba0a67c34870a2c"
    url = "https://github.com/JuliaBinaryWrappers/rocm_smi_lib_jll.jl/releases/download/rocm_smi_lib-v4.2.0+0/rocm_smi_lib.v4.2.0.x86_64-linux-musl-cxx11.tar.gz"
