# Autogenerated wrapper script for rocm_smi_lib_jll for x86_64-linux-musl-cxx03
export liboam, librocm_smi, rocm_smipy, rsmiBindingspy, rsmiBindingspylink

JLLWrappers.@generate_wrapper_header("rocm_smi_lib")
JLLWrappers.@declare_library_product(liboam, "liboam.so.1")
JLLWrappers.@declare_library_product(librocm_smi, "librocm_smi64.so.1")
JLLWrappers.@declare_file_product(rocm_smipy)
JLLWrappers.@declare_file_product(rsmiBindingspy)
JLLWrappers.@declare_file_product(rsmiBindingspylink)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        liboam,
        "oam/lib/liboam.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        librocm_smi,
        "rocm_smi/lib/librocm_smi64.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_file_product(
        rocm_smipy,
        "bin/rocm_smi.py",
    )

    JLLWrappers.@init_file_product(
        rsmiBindingspy,
        "rocm_smi/bindings/rsmiBindings.py",
    )

    JLLWrappers.@init_file_product(
        rsmiBindingspylink,
        "bin/rsmiBindings.py",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
